services:
    red-server:
        build:
            context: .
            dockerfile_inline: |
                FROM alpine:latest
                RUN apk add --no-cache nginx
                COPY ./src/red.html /etc/nginx/index.html
                RUN echo 'server { \
                    listen 80; \
                    server_name _; \
                    root /etc/nginx/; \
                    index index.html; \
                }' > /etc/nginx/http.d/default.conf
                EXPOSE 80
                CMD ["nginx", "-g", "daemon off;"]
        ports: 
         - 8001:80 
            
    blue-server:
        build:
            context: .
            dockerfile_inline: |
                FROM alpine:latest
                RUN apk add --no-cache nginx
                COPY ./src/blue.html /etc/nginx/index.html
                RUN echo 'server { \
                    listen 80; \
                    server_name _; \
                    root /etc/nginx/; \
                    index index.html; \
                }' > /etc/nginx/http.d/default.conf
                EXPOSE 80
                CMD ["nginx", "-g", "daemon off;"]
        ports: 
         - 8002:80 


    php-server:
        build: 
            context: .
            dockerfile_inline: |
                FROM alpine:latest
                RUN apk add --no-cache php
                WORKDIR /app
                RUN echo ' <?php \
                    phpinfo(); \
                    S?>' > /app/info.php
                EXPOSE 80
                CMD ["php", "-S", "0.0.0.0:80"]
        ports:
         - 8008:80