apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io/background
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://charts.rancher.io'
    chart: local-path-provisioner
    targetRevision: "0.0.28"
    helm:
      values: |
        storageClass:
          create: true
          name: local-path
          defaultClass: true
          reclaimPolicy: Delete
        nodePathMap:
          - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
            paths:
              - /opt/local-path-provisioner
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
